server {
    listen       3174;
    listen  [::]:3174;
    server_name  _;

    # Serve static client build
    root   /usr/share/nginx/html;
    index  index.html;

    # Try files and fallback to index.html for SPA routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache/static headers (optional)
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|webp|ico|woff2?)$ {
        expires 7d;
        access_log off;
    }
}

